"""add_audio_file_path_to_meeting

Revision ID: 1bf0a1ef0b85
Revises: 7c7550e2d45b
Create Date: 2026-01-29 05:29:47.296449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf0a1ef0b85'
down_revision: Union[str, None] = '7c7550e2d45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('audio_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'audio_file_path')
    # ### end Alembic commands ###
