"""add_status_to_meeting

Revision ID: 7c78715da1d6
Revises: 1bf0a1ef0b85
Create Date: 2026-01-29 05:31:54.517780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78715da1d6'
down_revision: Union[str, None] = '1bf0a1ef0b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'status')
    # ### end Alembic commands ###
