"""add_file_hash_to_meeting

Revision ID: 90f4345f2a1a
Revises: 7c78715da1d6
Create Date: 2026-02-02 01:23:17.157047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f4345f2a1a'
down_revision: Union[str, None] = '7c78715da1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_meetings_file_hash'), 'meetings', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_file_hash'), table_name='meetings')
    op.drop_column('meetings', 'file_hash')
    # ### end Alembic commands ###
