"""add missing meeting columns

Revision ID: a0ff3c623e1e
Revises: b79f55bcff7d
Create Date: 2026-02-06 02:52:01.757440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ff3c623e1e'
down_revision: Union[str, None] = 'b79f55bcff7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('meeting_type', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('attendees', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('writer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'writer')
    op.drop_column('meetings', 'attendees')
    op.drop_column('meetings', 'meeting_type')
    op.drop_column('meetings', 'duration')
    # ### end Alembic commands ###
