"""Add intermediate_summaries table

Revision ID: b79f55bcff7d
Revises: aead48c7fdac
Create Date: 2026-02-03 16:09:50.972889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b79f55bcff7d'
down_revision: Union[str, None] = 'aead48c7fdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intermediate_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intermediate_summaries_id'), 'intermediate_summaries', ['id'], unique=False)
    op.add_column('meetings', sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'meeting_date')
    op.drop_index(op.f('ix_intermediate_summaries_id'), table_name='intermediate_summaries')
    op.drop_table('intermediate_summaries')
    # ### end Alembic commands ###
