"""add_profile_fields

Revision ID: d66a257e837e
Revises: 90f4345f2a1a
Create Date: 2026-02-02 05:16:27.055263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66a257e837e'
down_revision: Union[str, None] = '90f4345f2a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('team_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_path')
    op.drop_column('users', 'team_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
